# https://hub.docker.com/_/postgres
version: '3'
services:
  postgres:
    image: postgres:13.2
    privileged: true
    container_name: postgresql
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - ./.pgsql_data:/var/lib/postgresql/data
      - ./pgsql_sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER       : ${PG_USER}
      POSTGRES_PASSWORD   : ${PG_PASS}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ                  : "Asia/Tokyo"
    hostname: postgres
    restart : always
    user    : root

